### ISSUE TITLE
Basic Reporting Now Errors E2E

### ISSUE THREAD

**Issue by wesley-trantham** [sgbj/jasmine-tfs-reporter#5]
```@angular/cli: 1.4.10
node: 8.9.1
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.10
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
jasmine-core:2.6.2,
typescript: 2.3.4
```
**Issue:** 
Error in `npm run e2e` in which the reporter has an error after any test run.

**Output**
```
DevTools listening on ws://127.0.0.1:12869/devtools/browser/9bfa7ea9-19c2-45ac-a9d0-01fe5037d488
Jasmine started

  tfs-reporter-test App
    √ should display welcome message

Executed 1 of 1 spec SUCCESS in 0.956 sec.
[08:05:12] E/launcher - Cannot read property 'getTime' of undefined
[08:05:12] E/launcher - TypeError: Cannot read property 'getTime' of undefined
    at Math.min.apply.testResults.specs.map.spec (C:\Users\user\Source\Repos\tfs-reporter-test\node_modules\jasmine-tfs-reporter\trx.js:42:79)
    at Array.map (<anonymous>)
    at module.exports (C:\Users\user\Source\Repos\tfs-reporter-test\node_modules\jasmine-tfs-reporter\trx.js:42:56)
    at TfsReporter.jasmineDone (C:\Users\user\Source\Repos\tfs-reporter-test\node_modules\jasmine-tfs-reporter\index.js:50:44)
    at dispatch (C:\Users\user\Source\Repos\tfs-reporter-test\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4522:28)
    at ReportDispatcher.jasmineDone (C:\Users\user\Source\Repos\tfs-reporter-test\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4493:11)
    at QueueRunner.onComplete (C:\Users\user\Source\Repos\tfs-reporter-test\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1029:18)
    at Immediate._onImmediate (C:\Users\user\Source\Repos\tfs-reporter-test\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4382:12)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[08:05:12] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! tfs-reporter-test@0.0.0 e2e: `ng e2e`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the tfs-reporter-test@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-01-23T14_05_12_330Z-debug.log
PS C:\Users\user\Source\Repos\tfs-reporter-test> [3840:22052:0123/080710.090:ERROR:process_metrics.cc(105)] NOT
IMPLEMENTED
[3840:22052:0123/080710.091:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[3840:22052:0123/080710.091:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[3840:22052:0123/080710.091:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[3840:22052:0123/080910.094:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[3840:22052:0123/080910.094:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[3840:22052:0123/080910.094:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[3840:22052:0123/080910.095:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
```
**Reproduction Steps**
Create new cli project `ng new tfs-reporter-test`
Add this library and configure protractor
`npm run e2e`

**Notes**
This was working great as of 2018-01-16. Our next run on 2018-01-18 suddenly saw this error. Nothing obvious was updated on our side. Since our project didn't have a `package-lock.json` file I'm unable to tell if a sub-dependency updated.

**Comment by sschalley** [comment]
I'm running into the same issue:

[08:43:23] E/launcher - Cannot read property 'getTime' of undefined
[08:43:23] E/launcher - TypeError: Cannot read property 'getTime' of undefined
    at Math.min.apply.testResults.specs.map.spec (C:\e2e\node_modules\jasmine-tfs-reporter\trx.js:42:78)
    at Array.map (native)
    at module.exports (C:\e2e\node_modules\jasmine-tfs-reporter\trx.js:42:56)
    at TfsReporter.jasmineDone (C:\e2e\node_modules\jasmine-tfs-reporter\index.js:50:44)
    at dispatch (C:\e2e\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4522:28)
    at ReportDispatcher.jasmineDone (C:\e2e\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4493:11)
    at QueueRunner.onComplete (C:\e2e\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1029:18)
    at Immediate.<anonymous> (C:\e2e\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4382:12)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
[08:43:23] E/launcher - Process exited with error code 199

**Comment by sgbj** [comment]
I'll look into this issue tonight.

**Comment by sgbj** [comment]
This should be fixed in 1.0.2. Please try it out and let me know if there are any issues. Thanks!

**Comment by sschalley** [comment]
I'm no longer seeing this issue. Thank you for the quick turnaround on the fix!!

**Comment by wesley-trantham** [comment]
Yes, thank you for fixing this! I'm now able to complete test runs again!
